### ISSUE TITLE
Include easy way to change groups when viewing a single group

### ISSUE THREAD

**Issue by arthurmcgregor** [TheCacophonyProject/cacophony-web-vuex#10]
Screenshot compares new/Vuex on the left and old version on the right. I like how it was easy to change groups in the old version. It was a bit clunky and didn't work so well on mobile, but I think it would be good to have similar in the new version also. If there isn't space for a full list of devices, perhaps a 'choose a different group' type button, or back-ish button, or maybe hide the groups list behind a \\/ arrow or something....

![groupcompare](https://user-images.githubusercontent.com/24260476/43164942-b0edac22-8fe6-11e8-8241-4f962f066461.png)

**Comment by arthurmcgregor** [comment]
@adbs1

**Comment by adbs1** [comment]
I've added a simple close button to the group view which takes you back to the groups page, in effect it acts like a popup. Have a play after it's committed and see what you think.

I messed with having the groups as an open/shut accordion style but after using it I opted for the simplicity of the group page.

**Comment by mjs** [comment]
@adbs1 the current approach looks good to me
