### ISSUE TITLE
User can be logged in without valid connection to API and no warnings show

### ISSUE THREAD

**Issue by arthurmcgregor** [TheCacophonyProject/cacophony-web-vuex#11]
So I realised this when I was reviewing the last PR. The app booted up fine and I could navigate to the Groups page, but it never went beyond 'Loading...' This was because I hadn't updated the app.config.js file (which is an easy fix no trouble)

However, it made me realise that if there is a problem with the API or the user's internet connection, they will still be logged in (because the data is in local storage) but the app will not work. I'm sure there is a way that this is usually dealt with, but I don't know what it is! Perhaps it is to implement better error handling every time the API is accessed, or perhaps it is part of the router authentication check...?? @adbs1

**Comment by arthurmcgregor** [comment]
I don't really know how to implement such a wrapper, but I understand the idea.

Would it pick up on all API errors? ie server vs connection vs authentication vs invalid format or other failures. Or would they be dealt with differently?

**Comment by adbs1** [comment]
Fixed with: https://github.com/TheCacophonyProject/cacophony-web-vuex/pull/13
