### ISSUE TITLE
Implement functionality of query recordings view

### ISSUE THREAD

**Issue by arthurmcgregor** [TheCacophonyProject/cacophony-web-vuex#12]
- [ ] Add ability to search for group of devices
- [ ] Fix bug where pagination number shows above menu (see screenshot below)
- [ ] Add loading wheel (or similar) when query is running
- [ ] Fix false positive search

![bug](https://user-images.githubusercontent.com/24260476/43439085-81ce1efa-94e5-11e8-90c9-d3cbcb995d18.png)

**Comment by mjs** [comment]
I have split these out into separate issues
