### ISSUE TITLE
Add loading wheel when query is running

### ISSUE THREAD

**Issue by mjs** [TheCacophonyProject/cacophony-web-vuex#28]

**Comment by adbs1** [comment]
The store 'fetching' properties are for this purpose. A loading style should be conditionally applied based on that value, an example can be found on in GroupAdd.vue

Obptaining the property:

    ...mapState({
      fetched: state => state.Groups.fetched
    })

And using the property:

<b-button
            :disabled="$v.form.$invalid || !fetched"
            type="submit"
            variant="primary">
            Add group
</b-button>
