### ISSUE TITLE
Notifications should pop above the UI

### ISSUE THREAD

**Issue by mjs** [TheCacophonyProject/cacophony-web-vuex#34]
They shouldn't push the rest of the page down.

**Comment by adbs1** [comment]
Hi Menno, in chrome, safari and firefox I'm seeing the notifications slide down over the current UI rather than pushing the UI down, are you describing that as the problem or are you actually having the rest of the page pushed down as well? If so what browser / env?

**Comment by mjs** [comment]
In Chrome and Firefox on multiple Linux machines they appear to push the UI down. In fact, sometimes you don't notice the notification because it's appears above the scroll position.

**Comment by mjs** [comment]
Never mind. I think we weren't using the latest code when we reviewed yesterday. I can see that this has been fixed.
