### ISSUE TITLE
Tag deletion doesn't work

### ISSUE THREAD

**Issue by mjs** [TheCacophonyProject/cacophony-web-vuex#36]

**Comment by adbs1** [comment]
Works for me @mjs. Is this still the case for you with the latest code?

**Comment by mjs** [comment]
I'm pretty sure this is an API server issue but I haven't confirmed yet. It seems like some tags can be deleted but others can't.

**Comment by arthurmcgregor** [comment]
I haven't found any faulty tag delete buttons this evening....

**Comment by mjs** [comment]
I've narrowed this down. It's an API server issue - see https://github.com/TheCacophonyProject/cacophony-api/issues/147
