### ISSUE TITLE
Include favicons in builds

### ISSUE THREAD

**Issue by mjs** [TheCacophonyProject/cacophony-web-vuex#52]
`index.template.ejs` currently refers to the favicons in `src/assets/favicon` which only works when the frontend is run in dev mode. Figure out how to get them included in the build and refer to them in the `dist` output instead. I'm pretty sure there's a way to get webpack to treat the favicons as dependencies so they get handled correctly.

**Comment by jimmykl** [comment]
This might be useful https://github.com/jantimon/favicons-webpack-plugin but my npm fu is weak. If we can use it tag me for the logo source .png
