### ISSUE TITLE
New prev/next icons generating Vue error

### ISSUE THREAD

**Issue by arthurmcgregor** [TheCacophonyProject/cacophony-web-vuex#73]
```
Unknown custom element: <font-awesome-layers> - did you register the component correctly? 
found in
---> <PrevNext> at src\components\Video\PrevNext.vue
       <RecordingView> at src\views\RecordingView.vue
         <App> at src\App.vue
           <Root>
```

#69 @jimmykl

**Comment by mjs** [comment]
I'm not seeing this error. Could it be that @arthurmcgregor needs to do a `npm install` to ensure all dependencies are installed?

**Comment by jimmykl** [comment]
I saw the error in the browser inspector console. I'm not familiar enough with vue atm to figure out what was happening so I used the same pattern as the FontAwesomeIcon component (#74) and the error disappeared.
