### ISSUE TITLE
Users list on GroupView.vue page is not populating

### ISSUE THREAD

**Issue by arthurmcgregor** [TheCacophonyProject/cacophony-web-vuex#9]
Screenshot compares new/Vuex on the left and old version on the right. As you can see, no user showing in user table when there should be.

![groupcompare](https://user-images.githubusercontent.com/24260476/43164942-b0edac22-8fe6-11e8-8241-4f962f066461.png)

I think the problem is groupData() computed property in GroupView.vue -> group.GroupUsers (which populates the b-table) doesn't exit. I think it should just use group.Users (group.Users.GroupUsers exists but doesn't have any useful info)

**Comment by arthurmcgregor** [comment]
(wrong button!)

@adbs1

**Comment by adbs1** [comment]
@arthurmcgregor I'm not seeing this, might have been fixed along the way, can you let me know if you're still seeing it?

**Comment by adbs1** [comment]
This was fixed some time ago
